# Tensors Basic Notes

### Imports

In [3]:
import torch
import numpy as np


### Tensors

Tensor - A high dimension array, the parent of smaller ones like the matrix, vector, or scalar

In [5]:
#Initialize a tensor

data = [[1,2],[3,4]]
x_data = torch.tensor(data) #Turns data into a tensor object
print(x_data)

tensor([[1, 2],
        [3, 4]])


**From Numpy:** Tensors can also be created from a numpy array.

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


Tensors can also be created from other tensors and data, like creating a tensor full of ones of the same size, or a random tensor.

In [7]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2166, 0.9145],
        [0.6244, 0.5589]]) 



**Shape:**  This is a tuple that determines dimensionality

In [16]:
#Each input consecutively adds a new dimension, so last value will be the length of a single array and it builds from there.
shape = (2,2,4,)
ones_tensor = torch.ones(shape)

print(f"Ones Tensor: \n {ones_tensor} \n")

Ones Tensor: 
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) 



### Attributes

**Attributes inlude:** Shape, data type, and the device it is stored on

In [18]:
shape = (3,4)
tensor = torch.rand(shape)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations

There are lots and lots of operations :(
All of these can run on gpu or cpu so you have to ensure its on the one you want

In [20]:
#Move to gpu if availible
if torch.accelerator.is_available():
    tensor = tensor.to("cuda")
    # can alo do: tensor.to(torch.accelerator.current_accelerator())
    print(f"Device tensor is stored on: {tensor.device}")


Device tensor is stored on: cuda:0


In [30]:
#Explore a few basic operations
tensor = torch.ones(4,4)
print(tensor)
print()

# Indexes
print(f"Row by first index: {tensor[0]}")
print(f"Column by first index: {tensor[:,0]}")
print(f"Row by last index: {tensor[-1]}")
print(f"Column by last index: {tensor[...,-1]}")
print()

#Altering rows and columns
tensor[:, -1] =0
tensor[2] = 0
print(tensor)
print()

#Concat - combine along a given dimension (torch.stack is another option)
combined = torch.cat([tensor, tensor, tensor], dim=1)
print(combined)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Row by first index: tensor([1., 1., 1., 1.])
Column by first index: tensor([1., 1., 1., 1.])
Row by last index: tensor([1., 1., 1., 1.])
Column by last index: tensor([1., 1., 1., 1.])

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 0.]])

tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])


In [35]:
# Matrix multiplication. - tensor.T returns a transpose of a tensor (flip rows and columns)
print(tensor)
print()
print(tensor.T)
print()
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)
print()
print(y2)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 0.]])

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [0., 0., 0., 0.]])

tensor([[3., 3., 0., 3.],
        [3., 3., 0., 3.],
        [0., 0., 0., 0.],
        [3., 3., 0., 3.]])

tensor([[3., 3., 0., 3.],
        [3., 3., 0., 3.],
        [0., 0., 0., 0.],
        [3., 3., 0., 3.]])


In [36]:
# Element multiplication
tensor2 = torch.ones(4,4)

mult = tensor * tensor2 # Can also use mult function
print(mult)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 0.]])


Sum and other tensor functions return a condensed tensor object. Using .item() gets the item and returns the desired value of the operation.

In [37]:
#Items and sum
agg = tensor.sum()
agg_item = agg.item()
print(agg)
print(agg_item)

tensor(9.)
9.0


#### Important Note

  - any operation ending in _ acts as in place like in matplotlib/pandas, applying the change to the tensor.